name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images
    - name: Deploy to minikube
      run: |
        kubectl apply -f k8s-node-app.yaml
        # Wait for the deployment to be ready
        echo "Waiting for deployment to be ready..."
        kubectl rollout status deployment/nodejs-app --timeout=120s
    - name: Debug pod status
      if: always()
      run: |
        echo "Checking pod status..."
        kubectl get pods -l app=nodejs-app -o wide
        echo "Checking pod logs..."
        kubectl logs -l app=nodejs-app --tail=50 || echo "No logs available"
        echo "Checking pod events..."
        kubectl describe pods -l app=nodejs-app
    - name: Test service URLs
      run: |
          minikube service list
          minikube service nodejs-app --url 